//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECom.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECom.Shared.Resources.LocalizedResource", typeof(LocalizedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account found matching given information.
        /// </summary>
        public static string account_found {
            get {
                return ResourceManager.GetString("account_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string actions {
            get {
                return ResourceManager.GetString("actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add announcement.
        /// </summary>
        public static string add_announcement {
            get {
                return ResourceManager.GetString("add_announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add role.
        /// </summary>
        public static string add_role {
            get {
                return ResourceManager.GetString("add_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Count.
        /// </summary>
        public static string admin_count {
            get {
                return ResourceManager.GetString("admin_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Permissions.
        /// </summary>
        public static string admin_permissions {
            get {
                return ResourceManager.GetString("admin_permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Roles.
        /// </summary>
        public static string admin_roles {
            get {
                return ResourceManager.GetString("admin_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admins.
        /// </summary>
        public static string admins {
            get {
                return ResourceManager.GetString("admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} is already deleted.
        /// </summary>
        public static string already_deleted {
            get {
                return ResourceManager.GetString("already_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} is already exists.
        /// </summary>
        public static string already_exists {
            get {
                return ResourceManager.GetString("already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} is already is in use.
        /// </summary>
        public static string already_in_use {
            get {
                return ResourceManager.GetString("already_in_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcements.
        /// </summary>
        public static string announcements {
            get {
                return ResourceManager.GetString("announcements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Changes.
        /// </summary>
        public static string apply_changes {
            get {
                return ResourceManager.GetString("apply_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZDK Network.
        /// </summary>
        public static string author_name {
            get {
                return ResourceManager.GetString("author_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorizing please wait....
        /// </summary>
        public static string authorizing {
            get {
                return ResourceManager.GetString("authorizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred. This application may no longer respond until reloaded..
        /// </summary>
        public static string blazor_error {
            get {
                return ResourceManager.GetString("blazor_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo.
        /// </summary>
        public static string cargo {
            get {
                return ResourceManager.GetString("cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string categories {
            get {
                return ResourceManager.GetString("categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string change_password {
            get {
                return ResourceManager.GetString("change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string company {
            get {
                return ResourceManager.GetString("company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Address.
        /// </summary>
        public static string company_address {
            get {
                return ResourceManager.GetString("company_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Information.
        /// </summary>
        public static string company_information {
            get {
                return ResourceManager.GetString("company_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string company_name {
            get {
                return ResourceManager.GetString("company_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset your password ?.
        /// </summary>
        public static string confirm_reset_password {
            get {
                return ResourceManager.GetString("confirm_reset_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset selected admin password ?.
        /// </summary>
        public static string confirm_reset_password_other_admin {
            get {
                return ResourceManager.GetString("confirm_reset_password_other_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string confirmation {
            get {
                return ResourceManager.GetString("confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Email Address.
        /// </summary>
        public static string contact_email {
            get {
                return ResourceManager.GetString("contact_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2022 - Today by ZDK Network. All Rights Reserved.
        /// </summary>
        public static string copyright {
            get {
                return ResourceManager.GetString("copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create announcement.
        /// </summary>
        public static string create_announcement {
            get {
                return ResourceManager.GetString("create_announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create role.
        /// </summary>
        public static string create_role {
            get {
                return ResourceManager.GetString("create_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical.
        /// </summary>
        public static string critical {
            get {
                return ResourceManager.GetString("critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datetime.
        /// </summary>
        public static string datetime {
            get {
                return ResourceManager.GetString("datetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Date.
        /// </summary>
        public static string delete_date {
            get {
                return ResourceManager.GetString("delete_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string disable {
            get {
                return ResourceManager.GetString("disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Url.
        /// </summary>
        public static string domain_url {
            get {
                return ResourceManager.GetString("domain_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string email_address {
            get {
                return ResourceManager.GetString("email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found.
        /// </summary>
        public static string empty_table {
            get {
                return ResourceManager.GetString("empty_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string enable {
            get {
                return ResourceManager.GetString("enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string end_date {
            get {
                return ResourceManager.GetString("end_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least one {name}.
        /// </summary>
        public static string ensure_one_element {
            get {
                return ResourceManager.GetString("ensure_one_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        public static string expiration_date {
            get {
                return ResourceManager.GetString("expiration_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire date.
        /// </summary>
        public static string expire_date {
            get {
                return ResourceManager.GetString("expire_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Link.
        /// </summary>
        public static string facebook_link {
            get {
                return ResourceManager.GetString("facebook_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal.
        /// </summary>
        public static string fatal {
            get {
                return ResourceManager.GetString("fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} field is invalid.
        /// </summary>
        public static string field_is_invalid {
            get {
                return ResourceManager.GetString("field_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2021 - Today by ZDK Network. All Rights Reserved.
        /// </summary>
        public static string footer_text {
            get {
                return ResourceManager.GetString("footer_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string forgot_password {
            get {
                return ResourceManager.GetString("forgot_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is the new generated password: {password}.
        /// </summary>
        public static string generated_new_password {
            get {
                return ResourceManager.GetString("generated_new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to home page.
        /// </summary>
        public static string go_to_home_page {
            get {
                return ResourceManager.GetString("go_to_home_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page you looking for is not found.
        /// </summary>
        public static string http_status_404 {
            get {
                return ResourceManager.GetString("http_status_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page you trying to view can not be viewed at the moment, a server error occurred. Please try again later or contact administration..
        /// </summary>
        public static string http_status_500 {
            get {
                return ResourceManager.GetString("http_status_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string images {
            get {
                return ResourceManager.GetString("images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram Link.
        /// </summary>
        public static string instagram_link {
            get {
                return ResourceManager.GetString("instagram_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error.
        /// </summary>
        public static string internal_error {
            get {
                return ResourceManager.GetString("internal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} is invalid.
        /// </summary>
        public static string invalid {
            get {
                return ResourceManager.GetString("invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fix the errors on the form before submitting..
        /// </summary>
        public static string invalid_form_submit {
            get {
                return ResourceManager.GetString("invalid_form_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} must be between {min}-{max} number of characters.
        /// </summary>
        public static string length_must_be_in_between {
            get {
                return ResourceManager.GetString("length_must_be_in_between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string list {
            get {
                return ResourceManager.GetString("list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Panel by ZDK Network.
        /// </summary>
        public static string login_page_message {
            get {
                return ResourceManager.GetString("login_page_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string management {
            get {
                return ResourceManager.GetString("management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max count has been reached {count}.
        /// </summary>
        public static string max_count_reached {
            get {
                return ResourceManager.GetString("max_count_reached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderator Permissions.
        /// </summary>
        public static string moderator_permissions {
            get {
                return ResourceManager.GetString("moderator_permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderator Roles.
        /// </summary>
        public static string moderator_roles {
            get {
                return ResourceManager.GetString("moderator_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} must be between {min}-{max}.
        /// </summary>
        public static string must_be_in_range {
            get {
                return ResourceManager.GetString("must_be_in_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select {name}.
        /// </summary>
        public static string must_select {
            get {
                return ResourceManager.GetString("must_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigating.
        /// </summary>
        public static string navigating {
            get {
                return ResourceManager.GetString("navigating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string new_password {
            get {
                return ResourceManager.GetString("new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No announcements found.
        /// </summary>
        public static string no_announcements_found {
            get {
                return ResourceManager.GetString("no_announcements_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found.
        /// </summary>
        public static string no_data_found {
            get {
                return ResourceManager.GetString("no_data_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} is not changed.
        /// </summary>
        public static string not_changed {
            get {
                return ResourceManager.GetString("not_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string not_found {
            get {
                return ResourceManager.GetString("not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} is added successfully.
        /// </summary>
        public static string ok_added {
            get {
                return ResourceManager.GetString("ok_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} is created successfully.
        /// </summary>
        public static string ok_created {
            get {
                return ResourceManager.GetString("ok_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} is deleted successfully.
        /// </summary>
        public static string ok_deleted {
            get {
                return ResourceManager.GetString("ok_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} is disabled successfully.
        /// </summary>
        public static string ok_disabled {
            get {
                return ResourceManager.GetString("ok_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} is enabled successfully.
        /// </summary>
        public static string ok_enabled {
            get {
                return ResourceManager.GetString("ok_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of {name} properties changed.
        /// </summary>
        public static string ok_not_changed {
            get {
                return ResourceManager.GetString("ok_not_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} is recovered successfully.
        /// </summary>
        public static string ok_recovered {
            get {
                return ResourceManager.GetString("ok_recovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} is updated successfully.
        /// </summary>
        public static string ok_updated {
            get {
                return ResourceManager.GetString("ok_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string old_password {
            get {
                return ResourceManager.GetString("old_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option.
        /// </summary>
        public static string option {
            get {
                return ResourceManager.GetString("option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Permissions.
        /// </summary>
        public static string owner_permissions {
            get {
                return ResourceManager.GetString("owner_permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner permissions can not be updated.
        /// </summary>
        public static string owner_permissions_can_not_be_updated {
            get {
                return ResourceManager.GetString("owner_permissions_can_not_be_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Roles.
        /// </summary>
        public static string owner_roles {
            get {
                return ResourceManager.GetString("owner_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already deleted.
        /// </summary>
        public static string p_already_deleted {
            get {
                return ResourceManager.GetString("p_already_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exists.
        /// </summary>
        public static string p_already_exists {
            get {
                return ResourceManager.GetString("p_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already in use.
        /// </summary>
        public static string p_already_in_use {
            get {
                return ResourceManager.GetString("p_already_in_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string p_invalid {
            get {
                return ResourceManager.GetString("p_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not changed.
        /// </summary>
        public static string p_not_changed {
            get {
                return ResourceManager.GetString("p_not_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string p_required {
            get {
                return ResourceManager.GetString("p_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel Settings.
        /// </summary>
        public static string panel_settings {
            get {
                return ResourceManager.GetString("panel_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords.
        /// </summary>
        public static string passwords {
            get {
                return ResourceManager.GetString("passwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must be same.
        /// </summary>
        public static string passwords_must_be_same {
            get {
                return ResourceManager.GetString("passwords_must_be_same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string payment {
            get {
                return ResourceManager.GetString("payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        public static string permission {
            get {
                return ResourceManager.GetString("permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission count.
        /// </summary>
        public static string permission_count {
            get {
                return ResourceManager.GetString("permission_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string permissions {
            get {
                return ResourceManager.GetString("permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string phone_number {
            get {
                return ResourceManager.GetString("phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Panel.
        /// </summary>
        public static string project_name {
            get {
                return ResourceManager.GetString("project_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover.
        /// </summary>
        public static string recover {
            get {
                return ResourceManager.GetString("recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirecting.
        /// </summary>
        public static string redirecting {
            get {
                return ResourceManager.GetString("redirecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Date.
        /// </summary>
        public static string register_date {
            get {
                return ResourceManager.GetString("register_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string reload {
            get {
                return ResourceManager.GetString("reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string remember_me {
            get {
                return ResourceManager.GetString("remember_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat New Password.
        /// </summary>
        public static string repeat_new_password {
            get {
                return ResourceManager.GetString("repeat_new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} field is required.
        /// </summary>
        public static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string reset_password {
            get {
                return ResourceManager.GetString("reset_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string result {
            get {
                return ResourceManager.GetString("result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string role {
            get {
                return ResourceManager.GetString("role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name.
        /// </summary>
        public static string role_name {
            get {
                return ResourceManager.GetString("role_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string roles {
            get {
                return ResourceManager.GetString("roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string save_changes {
            get {
                return ResourceManager.GetString("save_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        public static string select_language {
            get {
                return ResourceManager.GetString("select_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select permissions.
        /// </summary>
        public static string select_permissions {
            get {
                return ResourceManager.GetString("select_permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select theme.
        /// </summary>
        public static string select_theme {
            get {
                return ResourceManager.GetString("select_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected announcement.
        /// </summary>
        public static string selected_announcement {
            get {
                return ResourceManager.GetString("selected_announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error.
        /// </summary>
        public static string server_error {
            get {
                return ResourceManager.GetString("server_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to {action} {name} ?.
        /// </summary>
        public static string simple_dialog_confirmation {
            get {
                return ResourceManager.GetString("simple_dialog_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smtp.
        /// </summary>
        public static string smtp {
            get {
                return ResourceManager.GetString("smtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social media.
        /// </summary>
        public static string social_media {
            get {
                return ResourceManager.GetString("social_media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        public static string stock {
            get {
                return ResourceManager.GetString("stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been reset successfully.
        /// </summary>
        public static string success_password_reset {
            get {
                return ResourceManager.GetString("success_password_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Permissions.
        /// </summary>
        public static string support_permissions {
            get {
                return ResourceManager.GetString("support_permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Roles.
        /// </summary>
        public static string support_roles {
            get {
                return ResourceManager.GetString("support_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table is empty.
        /// </summary>
        public static string table_is_empty {
            get {
                return ResourceManager.GetString("table_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procuts sold Today.
        /// </summary>
        public static string today_sales_count {
            get {
                return ResourceManager.GetString("today_sales_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales earn Today.
        /// </summary>
        public static string today_sales_money {
            get {
                return ResourceManager.GetString("today_sales_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} can not be longer than {limit} characters.
        /// </summary>
        public static string too_long {
            get {
                return ResourceManager.GetString("too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} can not be shorter than {limit} characters.
        /// </summary>
        public static string too_short {
            get {
                return ResourceManager.GetString("too_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products sold Total.
        /// </summary>
        public static string total_sales_count {
            get {
                return ResourceManager.GetString("total_sales_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales earn Total.
        /// </summary>
        public static string total_sales_money {
            get {
                return ResourceManager.GetString("total_sales_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Factor.
        /// </summary>
        public static string two_factor {
            get {
                return ResourceManager.GetString("two_factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        public static string update_date {
            get {
                return ResourceManager.GetString("update_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string upload {
            get {
                return ResourceManager.GetString("upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string url {
            get {
                return ResourceManager.GetString("url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urls.
        /// </summary>
        public static string urls {
            get {
                return ResourceManager.GetString("urls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string warn {
            get {
                return ResourceManager.GetString("warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web API Url.
        /// </summary>
        public static string web_api_url {
            get {
                return ResourceManager.GetString("web_api_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to {companyName}.
        /// </summary>
        public static string welcome_message {
            get {
                return ResourceManager.GetString("welcome_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whatsapp.
        /// </summary>
        public static string whatsapp {
            get {
                return ResourceManager.GetString("whatsapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password.
        /// </summary>
        public static string wrong_password {
            get {
                return ResourceManager.GetString("wrong_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new password: {password}.
        /// </summary>
        public static string your_new_password {
            get {
                return ResourceManager.GetString("your_new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube Link.
        /// </summary>
        public static string youtube_link {
            get {
                return ResourceManager.GetString("youtube_link", resourceCulture);
            }
        }
    }
}
